sudo: false

cache:
  directories:
    - node_modules

language: node_js

node_js:
  - 'lts/*'

script:
  - npm run lint
  - npm run test:coveralls
  
notifications:
  email:
    recipients:
      - dalvo_rsn@hotmail.com
    on_success: never
    on_failure: always
