version: "3.6"

services:
  mongodb:
    image: mongo:4.4.3-bionic
    ports:
      - ${MONGO_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    volumes:
      - mongo-db-data:/data/db

volumes:
  mongo-db-data: